#!/bin/bash
#SBATCH --job-name=alexAgilent
#SBATCH --account=aa20
#SBATCH --time=00:05:00
#SBATCH --ntasks=1
#SBATCH --mem-per-cpu=4096
#SBATCH --cpus-per-task=1
module load anaconda
module load cuda/10.1
source activate /projects/bw83/anley1/conda_envs/swinEnv/
#python tools/test.py configs/bead/type2/faster_rcnn_x101_64x4d_fpn_1x_coco.py freeze/save1/faster_rcnn_x101_64x4d_fpn_1x_coco_type_2/latest.pth --eval bbox --out ./results2/type2/faster_rcnn_x101_64x4d_fpn_1x_coco.pkl --show-dir ./results2/test_image/type2/faster_rcnn_x101_64x4d_fpn_1x_coco
#python tools/test.py configs/bead/type2/cascade_rcnn_x101_64x4d_fpn_1x_coco.py freeze/save1/cascade_rcnn_x101_64x4d_fpn_1x_coco_type_2/latest.pth --eval bbox --out ./results2/type2/cascade_rcnn_x101_64x4d_fpn_1x_coco.pkl --show-dir ./results2/test_image/type2/cascade_rcnn_x101_64x4d_fpn_1x_coco
#python tools/test.py configs/bead/type2/ssd512_coco.py freeze/save1/ssd512_coco_type_2/latest.pth --eval bbox --out ./results2/type2/ssd512_coco.pkl --show-dir ./results2/test_image/type2/ssd512_coco
## python tools/test.py configs/bead/cornernet_hourglass104_mstest_32x3_210e_coco.py freeze/save1/cornernet_hourglass104_mstest_32x3_210e_coco/latest.pth --eval bbox --out ./results2/results_wo_chamber/cornernet_hourglass104.pkl
#python tools/test.py configs/bead/type2/yolov3_d53_mstrain-608_273e_coco.py freeze/save1/yolov3_d53_mstrain_type_2/latest.pth --eval bbox --out ./results2/type2/yolov3_d53_mstrain.pkl --show-dir ./results2/test_image/type2/yolov3_d53_mstrain
#python tools/test.py configs/bead/type2/retinanet_x101_64x4d_fpn_1x_coco.py freeze/save1/retinanet_x101_64x4d_fpn_1x_coco_type_2/latest.pth --eval bbox --out ./results2/type2/retinanet_x101_64x4d_fpn_1x_coco.pkl --show-dir ./results2/test_image/type2/retinanet_x101_64x4d_fpn_1x_coco
#python tools/test.py configs/bead/type2/libra_faster_rcnn_x101_64x4d_fpn_1x_coco.py freeze/save1/libra_faster_rcnn_x101_64x4d_fpn_1x_coco_type_2/latest.pth --eval bbox --out ./results2/type2/libra_faster_rcnn_x101_64x4d_fpn_1x_coco.pkl --show-dir ./results2/test_image/type2/libra_faster_rcnn_x101_64x4d_fpn_1x_coco
python tools/test.py freeze/htc_hrnet_type_5_OHEM/htc_hrnetv2p_w40_28e_coco_type_5_on_type_3.py freeze/htc_hrnet_type_5_OHEM/latest.pth --eval bbox --out results/pkl_files/htc_hrnet_type_5_OHEM_v2.pkl --show-dir results/show_dirs/htc_hrnet_type_5_OHEM_v2
#python tools/test.py configs/bead/cascade_rcnn_hrnetv2p_w32_20e_coco.py freeze/save1/cascade_rcnn_hrnetv2p_w32_20e_coco_type_2/latest.pth --eval bbox --out ./results2/type2/cascade_rcnn_hrnetv2p_w32_20e_coco.pkl --show-dir ./results2/test_image/type2/cascade_rcnn_hrnetv2p_w32_20e_coco
