#!/bin/bash
#SBATCH --job-name=alexAgilent
#SBATCH --account=aa20
#SBATCH --time=02:00:00
#SBATCH --ntasks=8
#SBATCH --mem-per-cpu=4096
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=1
#SBATCH --gres=gpu:2
#SBATCH --partition=m3g
module load anaconda
module load cuda/10.1
source activate /projects/bw83/anley1/conda_envs/swinEnv/
#python tools/train.py configs/bead/faster_rcnn_x101_64x4d_fpn_1x_coco.py --work-dir freeze/faster_rcnn_x101_64x4d_fpn_1x_coco_type_2
# python tools/train.py configs/bead/type2/cascade_rcnn_x101_64x4d_fpn_1x_coco.py --work-dir freeze/save1/cascade_rcnn_x101_64x4d_fpn_1x_coco_type_2
# python tools/train.py configs/bead/type2/ssd512_coco.py --work-dir freeze/save1/ssd512_coco_type_2
# python tools/train.py configs/bead/type2/cornernet_hourglass104_mstest_32x3_210e_coco.py --work-dir freeze/save1/cornernet_hourglass104_mstest_32x3_210e_coco_type_2
#python tools/train.py configs/bead/type2/yolov3_d53_mstrain-608_273e_coco.py --work-dir freeze/save1/yolov3_d53_mstrain_type_2
#python tools/train.py configs/bead/type2/cascade_rcnn_hrnetv2p_w32_20e_coco.py --work-dir freeze/save1/cascade_rcnn_hrnetv2p_w32_20e_coco_type_2_v2
#python tools/train.py configs/bead/type2/libra_faster_rcnn_x101_64x4d_fpn_1x_coco.py --work-dir freeze/save1/libra_faster_rcnn_x101_64x4d_fpn_1x_coco_type_2
#python tools/train.py configs/bead/type2/retinanet_x101_64x4d_fpn_1x_coco.py --work-dir freeze/save1/retinanet_x101_64x4d_fpn_1x_coco_type_2
#python tools/train.py configs/bead/type2/dh_faster_rcnn_x101_64x4d_fpn_1x_coco_v2.py --work-dir freeze/save1/dh_faster_rcnn_x101_64x4d_fpn_1x_coco_v2
#python tools/train.py configs/bead/cascade_mask_rcnn_hrnetv2p_w40_20e_coco.py --work-dir freeze/cascade_mask_rcnn_hrnetv2p_w40_20e_coco_grayscale
./tools/slurm_train.sh m3g alexAgilent configs/bead/cascade_mask_rcnn_hrnetv2p_w40_20e_coco.py freeze/train_8GPU_combined_lr002 8
#python tools/train.py configs/bead/cascade_mask_rcnn_x101_32x4d_fpn_1x_coco.py --work-dir freeze/cascade_mask_rcnn_x101_32x4d_fpn_1x_coco
# python tools/train.py configs/bead/cascade_mask_rcnn_swin_base_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.py --work-dir freeze/cascade_mask_rcnn_swin_base_pretrain_22k
# python tools/train.py configs/bead/cascade_mask_rcnn_swin_small_patch4_window7_mstrain_480-800_giou_4conv1f_adamw_3x_coco.py --work-dir freeze/cascade_mask_rcnn_swin_small_pretrain_22k
